### PR TITLE
Add pyproj regridding post

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Follow up post to #39 to show how to regrid using `pyproj`

https://nbviewer.org/github/coecms/coecms.github.io/blob/064224a3d32292c78819a12bbb6d798dca6181c9/notebooks/2021-11-02-pyproj-regrid.ipynb

### CODE REVIEW

**Comment by ScottWales** [comment]
cell 4: this can also of course be done with  `data[0::50,0::50].bed.plot(size=8);`, using isel makes it clear which axes are being reduced

Briefly explain why the tripole is important for non-oceans folks - grid in the ocean is distorted around the arctic ocean to move the pole onto land, doesn't affect southern hemisphere

Briefly explain the algorithm before you get started to get readers situated- projecting the ocean grid to data coordinates, find the depth at that point.

What are the alternatives (e.g. xesmf) and why can't they be used here?

**Comment by aidanheerdegen** [comment]
Thanks @ScottWales, all good suggestions. See updated notebook:

https://nbviewer.org/github/coecms/coecms.github.io/blob/f637ae182a9d78e7cc86034d09efe207ba5ed685/notebooks/2021-11-02-pyproj-regrid.ipynb

**Comment by aidanheerdegen** [comment]
Updated update

https://nbviewer.org/github/coecms/coecms.github.io/blob/d42833c53b3e913e64d421a1e451a2982ceeceb5/notebooks/2021-11-02-pyproj-regrid.ipynb

**Review by ScottWales — APPROVED** [review]
Looks good, thanks @aidanheerdegen

**Pull request merged**
