### PR TITLE
Api calculation from code break

### PR DESCRIPTION
**Pull request by ScottWales**
https://nbviewer.org/github/coecms/coecms.github.io/blob/api/posts/2021-11-24-api.ipynb

### CODE REVIEW

**Comment by paolap** [comment]
Minors:
In "Convert to a function"
consolodate change to consolidate 

I would probably change this in the dask section: 
from " if we're chunked horizontally" to "if the data is chunked horizon.tally"

**Comment by ccarouge** [comment]
There are some weird formatting issues in the Markdown. Starting at {admonition} before "Why the .load()?". At other places, some {func} appear. And the formatting of the Markdown after cell 13 is wrong:
```
{note}
Remember that everything on the right side of an assignment `=` gets evaluated before the variable is assigned, so in
```python
api = api_at_year(precip, '1981', previous_api = api)
```

**Comment by ScottWales** [comment]
Those are special markups for jupyter-book that nbviewer doesn't understand - https://jupyterbook.org/content/content-blocks.html#notes-warnings-and-other-admonitions

**Comment by ccarouge** [comment]
Do we want to compare the speed of each method or not?

I think I'd like to see a bit of a conclusion. Is it worth going with the Pure Dask method even if the load method works?

**Comment by aidanheerdegen** [comment]
I was going to say, could do with some `%%time` specials, if only to give people an idea of how long the calculations should take.

**Comment by aidanheerdegen** [comment]
Can the plots be a bit bigger? The default size is a bit small IMO.

**Comment by aidanheerdegen** [comment]
If it is on the slow side might be worth using `numba` or `scipy.signal`. This SO has a bunch of examples, some of which though not strictly relevant have some timing information

https://stackoverflow.com/questions/42869495/numpy-version-of-exponential-weighted-moving-average-equivalent-to-pandas-ewm

specifically:

https://stackoverflow.com/a/59199643/4727812

here is the `scipy.signal` solution without a window:

https://stackoverflow.com/a/47971187/4727812

**Comment by ScottWales** [comment]
I think we're more worried about memory management than computation time, though those are good to know about

**Comment by ScottWales** [comment]
Thanks all for comments, current version is https://nbviewer.org/github/coecms/coecms.github.io/blob/d1cb010d362995428fa628fd4d8145a011bf23df/posts/2021-11-24-api.ipynb

**Pull request merged**
