### PR TITLE
Update storage

### PR DESCRIPTION
**Pull request by paolap**
Bigger updates:

- I've added Grafana and removed ncimonitor
- I'm mentioning dci-file-expiry in the Where section 
- Added ACCESS Archiver tool
Not solved yet:

- location of um2netcdf.py in the UM history files section

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Some comments I have are from my original blog, as I just adapted it from slides. e.g.

> intermediate data for analysis (keep scripts to regenerate (version control))

Change to "intermediate data for analysis (keep scripts to regenerate under version control, ideally on GitHub or similar)"

and 

> You can put large amounts of data with netmv / netcp. Makes tar file of a directory, can be slow and increase disk usage in short term. Data must be retrieved in large quanta. Using mdss to transfer as-is will generally time out before all data is transferred.

Change to 

"You can put large amounts of data with netmv / netcp. These tools make a tar file of the directory you are trying to move, can be slow and increase disk usage dramatically in short term. Data must also be retrieved again in large quanta. This is usually not recommended.

Using the `mdss` command to transfer on a login node will generally time out before all data is transferred. So the best option is probably to use an interactive PBS job, or create a script, and use `mdss put -r`."



Might be worth mentioning bit grooming after packing. Maybe something like:

Bit Grooming/Shaving/Precision-Preserving Compression

[Bit grooming](https://gmd.copernicus.org/articles/9/3199/2016/) is a form of precision-preserving compression, similar to packing, but does not suffer from the degradation of precision within the narrow dynamic range of values chosen. It is an active area of research, and new algorithms/approaches are being developed. Generally these approaches remove spurious precision from scientific data, usually model output, that has no informational value, and by doing so makes the data more compressible. In a real-world application the data was less than half the size of the same data only using compression.


`um2netcdf` is available under `/g/data/access/projects/access/modules/pythonlib/um2netcdf4`

So
```
module use /g/data/access/projects/access/modules/
module load pythonlib/um2netcdf4
```

It seems CSIRO use Iris in their `netcdf_conversion` process in rose+cylc. @HoWol76 may be able to find out more details about that.

https://confluence.csiro.au/display/ACCESS/Using+CM2+suites+in+Rose+and+Cylc

**Comment by ccarouge** [comment]
For netcdf conversion from ACCESS outputs, normally, there is the post-processing script from Chloe that has been added to the standard suites.

**Comment by paolap** [comment]
Thanks for the review I applied the changes. @ccarouge I already mentioned the  the ACCESS Archiver from Chloe, this is the first step of her post-processing tool, which is the one that transfer, convert, compress the files.

**Comment by ccarouge** [comment]
I know you haven't asked for me to review the post but now that I'm here, I'm going to comment anyway. I also know what I'm going to comment on isn't necessarily bits you have updated and might date from the previous post.

In "Why?". It starts with "Why do I have these?" and I don't understand this at all without reading further. Maybe the question is better asked as "Why do I produce this data?"

In "How?". In Delete, we should add the case of erroneous simulation. It seems obvious but we know some people still keep the data. 

In Packing. What does this mean: "Useful when data is produced: problems can be corrected and data regenerated." ?

For um2netcdf:
```
$module use ~access/modules
$module load pythonlib/um2netcdf4
$um2netcdf4.py ....
```

Here: "Some models produce large numbers of files, e.g. one per time step. Dimensional information and metadata is repeated, so it is redundant, this approach saves on space as well." It might be better to say: "this approach can save a lot of storage space as well"

**Comment by paolap** [comment]
All reviews are welcome and yes I focused only on updating the commands that didn't work anymore and adding references to new tools. I've added all the suggestions and double checked it builds fine.

**Review by aidanheerdegen — APPROVED** [review]

**Pull request merged**
