### PR TITLE
How to improve code design

### PR DESCRIPTION
**Pull request by ccarouge**
Lots of people at the Centre tend to copy-paste a lot of lines of codes instead of using functions / dictionaries / classes. 
This is to try and explain how to do it via an example.

### CODE REVIEW

**Comment by ScottWales** [comment]
Maybe open the datasets with `chunks={}` just so it's not displaying the arrays of data in the output

get_vars function can omit the glob I believe to simplify it:
```
# Define a function to read in the data
def get_var(path, varname):
    """Reads in all the netcdf files in the input path and return the data for the selected variable
    path: pathlib.Path, path to the netcdf files
    varname: string, name of the variable to select in the netcdf files"""
    
    ds = xr.open_mfdataset(path / "*.nc")
    
    return ds[varname]
```

**Comment by ccarouge** [comment]
@ScottWales I tried without the glob() but open_mfdataset() complains then:
```
>>> tt = Path("/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA/")
>>> nc_files = tt/"*.nc" 
>>> nc_files
 PosixPath('/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA/*.nc')
>>> import xarray as xr
>>> xr.open_mfdataset(nc_files)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/backends/api.py", line 870, in open_mfdataset
    paths = [str(p) if isinstance(p, Path) else p for p in paths]
TypeError: 'PosixPath' object is not iterable
```
I believe it needs the glob() to expand the pattern.

**Comment by ScottWales** [comment]
ah right, makes sense. Other option is `xr.open_mfdataset(str(nc_files))` - it's cause Path works differently to plain strings

**Comment by aidanheerdegen** [comment]
In this example I'd be tempted to not use a dict, as it is the experiment names that are the variable you want to use. So something like this
```python
experiments = ['historical', 'picontrol']

IPSL_path = Path("/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA")
expt_path = "r1i1p1f1/Lmon/tsl/gr/v20200729/"
variable = "tsl"

# Dict to store the experiments with the experiment name as they key and data
# as the value
data = {}
for expt in experiments:
    data[expt] = get_var(IPSL_path / expt / expt_path), variable).isel(solth=0).load()

# Restrict the data to the longest common time window.
data["picontrol"] = data["picontrol"].sel(time=data["historical"].time)
```

Edit: When I said "not use a dict" I meant for storing the experiment names, clearly I'm advocating using one for storing the data. It goes without saying that it would then be possible to also iterate over an array of variable names when loading the data. If I did this not sure I'd have a `.load()` in there, could run out of memory pretty easily.

**Comment by aidanheerdegen** [comment]
Following on from above, maybe it makes sense to do this off the bat, to show it could be done, but only use a single variable? Too complex?
```python
from collections import defaultdict

experiments = ["historical", "picontrol"]

IPSL_path = Path("/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA")
expt_path = "r1i1p1f1/Lmon/tsl/gr/v20200729/"
variables = ["tsl", ]

# Dict to store the experiments with the experiment name and variable names
# as the keys and data as the value
data = defaultdict()

for expt in experiments:
    for var in variables:
        data[expt][var] = get_var(IPSL_path / expt / expt_path), var).isel(solth=0).load()

# Restrict the data to the longest common time window.
for var in variables:
    data["picontrol"][var] = data["picontrol"][var].sel(time=data["historical"][var].time)

for expt in experiments:
    for var in variables:
        display(data[expt][var])
```

**Comment by ccarouge** [comment]
@aidanheerdegen I thought of something like that until I realised the version in the path "v20200729" isn't common to both experiments. It's possible for `experiments` to be a list of tuples and use the tuple elements to build the path. I guess using the tuple route is a bit over the top in the example, but it is the easiest to generalise. But I'll add a disclaimer that the best way to run an analysis with lots of different CMIP data is to use Clef to get the path info.

I have removed the `.load()` following Scott's comment. I haven't updated the code as it was the only change.

**Comment by aidanheerdegen** [comment]
Ah, hadn't noticed the difference in path. Agreed `clef` is the right way to do it, and it isn't hard to have experiment/version key/values in a dict, but it starts to look a lot less compact that the original! 

Ok, then I'd say just lightly modify what I suggested before":
```python
# Paths to 2 CMIP6 model experiments
IPSL_path = Path("/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA/")

variable = 'tsl'

experiments = {
    "historical": IPSL_path / "historical/r1i1p1f1/Lmon" / variable / "gr/v20200729/",
    "picontrol": IPSL_path / "piControl/r1i1p1f1/Lmon" / variable / "gr/v20210216/",
}

# Dict to store the experiments with the experiment name as they key and data
# as the value
data = {}
for expt, path in experiments.items():
    # Find all netcdf files in those directories. 
    data[expt] = get_var(path, variable).isel(solth=0).load()

# Restrict the data to the longest common time window.
data["picontrol"] = data["picontrol"].sel(time=data["historical"].time)

for expt in experiments:
    display(data[expt]
```

**Comment by ccarouge** [comment]
@aidanheerdegen @ScottWales I've reworked the notebook. I've integrated Aidan's comments. I have also added more explanations about what is bad in the original code and why the second version is better.

**Comment by aidanheerdegen** [comment]
Tiny typo:
```python
for expt, path in experiments.items():
    # Find all netcdf files in those directories and restric the data to the surface layer.
    data[expt] = get_var(path, variable).isel(solth=0)
```
`restric` is missing the at the end in the inline comment

With the panel plots at the end, it would be nice if the plots were larger compared to the shared colorbar. Maybe just increase the `size`?

**Comment by ccarouge** [comment]
@aidanheerdegen I've made the changes following your comment. Good to go?

**Comment by aidanheerdegen** [comment]
Yeah good to go!

**Pull request merged**
