### PR TITLE
add animation notebook

### PR DESCRIPTION
**Pull request by HoWol76**
Add blog post about creating animations with python

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
I'm off sick at the moment so you may need to ask someone else to review

**Comment by ccarouge** [comment]
See my commit. Since changes to notebooks are difficult to track, here is a summary:

 - Needs sections! There are 2 obvious sections: animated gifs, animation within Python. 
See changes between cells 5 and 6, and between 12 and 13
 - Cell 1: "Matplotlib needed to plot the dataset, etc" -> "Pyplot needed to plot the dataset, etc". Animation and pyplot are both parts of matplotlib. (Change made)
 - Cell 2: Would it be better to use an open dataset (no license) so you can use an opendap url and anyone can run the notebook? For example: I can't review it locally. (To be done if wanted)
 - Text between cell 8 and 9: "We will be using higher test numbers [in the file names] to distinguish between animations." Without mention of the file names, one wonders what number you are talking about. (Change made)
 - Text between cells 12  and 13: "The animation is trickier [...] but it's also a lot shorter." Shorter in what way? Shorter to run or shorter to write? (To be done)
 - Cell 13: "that updates the values for the colormesh" would it be clearer to say "that updates the values for each frame" ? (To be done)
 - Finally, you need to mention this: http://christopherbull.com.au/mkmov/ It has been developed by someone at the Centre and would probably be useful to a lot of people. It does more than the simple method you highlight here. It might even be better to recommend using this rather than the direct method (but I haven't used it or looked much into it so maybe not).

**Comment by HoWol76** [comment]
I've incorporated the suggestions by Claire that she hasn't already included herself. The dataset has been changed to one of the xarray tutorial datasets, also, I've added the animated gifs and the mp4 file to the repository, so it hopefully should show up properly.

**Comment by ccarouge** [comment]
Since you changed the dataset, you need to change the description at the top of the blogpost. 
Would it be worth adding one last example with interpolated contours instead of a raster map? People usually only use raster maps for debugging not for presenting.
If you strongly recommend MkMov, I would put it at the start:
"In this post, we will be discussing how to animate a 2D field. We'll go step by step through 2 possibilities in Python. But we strongly recommend MkMov etc. Especially, this tool can provide more than simple animations of 2D fields if required. [etc...]" Or something like that.
And I've changed some minor things in the text.

**Comment by HoWol76** [comment]
I don't know much about Christopher's script at all. I've never even seen it before you told me about it. Maybe I shouldn't 'strongly recommend' something I don't know.

I have looked at contour maps, and I see even less on them than on the raster map.

**Pull request merged**
