### PR TITLE
Add post about using apply_along_axis on multiple arrays

### PR DESCRIPTION
**Pull request by ScottWales**

### CODE REVIEW

**Comment by ScottWales** [comment]
@ccarouge can you please review my post's notebook

https://github.com/coecms/coecms.github.io/blob/a3602ee4f53b256be68216f6c8544a8d16d33942/notebooks/2019-07-29-multi-apply-along-axis.ipynb

**Comment by ccarouge** [comment]
It's good. I'm just wondering if it would be worth putting some tests in to check the shapes and sizes of the arrays are compatible. I'm not sure what would be the best way to do that.

Also, do you intend to propose it as an addition to numpy eventually? (nothing to do with the blog post itself)

**Comment by ScottWales** [comment]
The intent is that if they're not compatible then there will be an error in the `concatenate` call. I'll make this explicit.

It would be nice to get this into numpy since it seems to be coming up a bit, probably won't get to it in the near future though

**Comment by ccarouge** [comment]
Can you add section titles: Function definition, Example, Error handling? You can choose what you want, obviously.

**Pull request merged**
