### PR TITLE
xesmf.regridder blog post

### PR DESCRIPTION
**Pull request by annettehirsch**

### CODE REVIEW

**Comment by ScottWales** [comment]
nbviewer- https://nbviewer.jupyter.org/github/coecms/coecms.github.io/blob/annette/notebooks/2021-04-09-xesmf-regrid.ipynb

**Comment by ScottWales** [comment]
looks good to me - i might add that if you're comparing against another dataset, you can use a field from that dataset as ds_out directly

**Comment by annettehirsch** [comment]
true! worth fixing or leave as is?

**Comment by ScottWales** [comment]
if it's quick to do - relates to the ticket aidan was looking at the other day. if it's a bother I'm fine leaving as is

**Comment by ScottWales** [comment]
it's fine to just say it in the text, no need to demo it

**Pull request merged**
