### PR TITLE
Review Danny's shiny blog post

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Hey @RavDanny 

I figured I just do this a PR.

This change

https://github.com/coecms/coecms.github.io/compare/dannyreview?expand=1#diff-13ffafa07c471cb4aa710995dce49c02R111

was to avoid confusion, as the comment in the original breaks the code and means it can't be easily cut n' pasted.

Perhaps using a dataset that anyone can access. Here are some publicly available climate extreme datasets

https://www.metoffice.gov.uk/hadobs/hadghcnd/download.html

Tmax is only 2.2MB

https://www.metoffice.gov.uk/hadobs/hadghcnd/data/HadGHCND_1949-2011_TXx.nc.gz

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Using the latest RStudio (RStudio 1.1.456 - Mac OS X 10.6+ (64-bit)) required a fair bit of compilation from source of the required packages. I don't know if that is just because I am using the latest version and there aren't yet binary build available. Which is why I added that bit about compilation

**Comment by RavDanny** [comment]
Thanks, @aidanheerdegen 

Regarding your suggestion re: line 119, that wasn't quite what I had in mind, but rather that the reader leave `shinyApp(ui, server)` in the code as before and then click `Run App`. 

If I say that explicitly, (i.e. "Leave `shinyApp(ui,server)` at the bottom of the code as is and then click `Run App`.) do you think that would be understood?

**Comment by aidanheerdegen** [comment]
I don't think I had a "Run App" button. Maybe I did something wrong? You should do what you think is right and not waste too much time on what I've suggested.

**Comment by aidanheerdegen** [comment]
So don't bother with this PR if it is too complicated, we can just close it

**Pull request closed without merging**
